# Site settings
title:       abhinav tushar
email:       abhinav.tushar.vs@gmail.com
author:      Abhinav Tushar
description: "Personal Blog"
baseurl:     ""
url:         "http://lepisma.github.io/"

# Google analytics
google_analytics:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Contact pane
contact_form: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
