# Site settings
title: abhinav tushar
email: "http://www.google.com/recaptcha/mailhide/d?k=01W7yEHzyTvX_53exlt1qAuA==&c=O0AuJ2jg76zNyKQn-yopyNqo14LwVT9bzsCV1TKL_po="
author: Abhinav Tushar
description: Personal Blog
baseurl: ""
url: https://lepisma.github.io/

links:
  twitter: https://twitter.com/AbhinavTushar
  github: https://github.com/lepisma
  lastfm: https://last.fm/user/AbhinavTushar
  protonmail: "http://www.google.com/recaptcha/mailhide/d?k=01NVJUzT0e9SIORBtXMwhALg==&c=mHrHE3EkS-j9YfYpcxgN9odQALvtwLhnC8CDvjU8U6g="
  keybase: https://keybase.io/lepisma

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true
gems:
  [jekyll-paginate]
