# Site settings
title: abhinav tushar
email: https://spamty.eu/mail/v4/523/4tWg0Jz3Naf7d0b78b/
author: Abhinav Tushar
description: Personal Blog
baseurl: ""
url: https://lepisma.github.io/

links:
  twitter: https://twitter.com/AbhinavTushar
  github: https://github.com/lepisma
  lastfm: https://last.fm/user/AbhinavTushar
  protonmail: https://spamty.eu/mail/v4/524/MsKhLU2xUJb042f97f/
  keybase: https://keybase.io/lepisma

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true
plugins:
  - jekyll-paginate