# Site settings
title: abhinav tushar
email: https://lepisma.github.io/about#contact
author: Abhinav Tushar
description: Personal Blog
baseurl: ""
url: https://lepisma.github.io/

links:
  github: https://github.com/lepisma
  lastfm: https://last.fm/user/AbhinavTushar
  keybase: https://keybase.io/lepisma

# Build settings
livereload: true
exclude: ['_org']
markdown: kramdown
permalink: pretty
paginate: 5
excerpt_separator: "<!--more-->"
sass:
  compressed: true
tag_page_layout: tag_page
tag_page_dir: archive
