# Site settings
title: abhinav tushar
email: https://keybase.io/lepisma
github: https://github.com/lepisma
author: Abhinav Tushar
description: Personal Blog
baseurl: ""
url: https://lepisma.github.io/

# Build settings
livereload: true
exclude: ['_org']
markdown: kramdown
permalink: pretty
paginate: 5
excerpt_separator: "<!--more-->"
sass:
  compressed: true
tag_page_layout: tag_page
tag_page_dir: archive
